name: App Flutter CI/CD

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.0

      - run: flutter pub get

      - run: flutter test

      - run: flutter build apk --release
      - run: flutter build appbundle --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
